export const winningPtLists = [
  {
    id: 1,
    winningName: "corners",
    winningLabel: "Corners",
    checked: false,
    winnerName: "",
    description: "first and last digit of first and last row",
  },
  {
    id: 2,
    winningName: "firstLine",
    winningLabel: "First Line",
    checked: false,
    winnerName: "",
    description: "All Digits of first row in ticket",
  },
  {
    id: 3,
    winningName: "secondLine",
    winningLabel: "Second Line",
    checked: false,
    winnerName: "",
    description: "All Digits of second row in ticket",
  },
  {
    id: 4,
    winningName: "thirdLine",
    winningLabel: "Third Line",
    checked: false,
    winnerName: "",
    description: "All Digits of third row in ticket",
  },
  {
    id: 5,
    winningName: "breakfast",
    winningLabel: "Breakfast",
    checked: false,
    winnerName: "",
    description: "All Digits of first three columns in ticket",
  },
  {
    id: 6,
    winningName: "lunch",
    winningLabel: "Lunch",
    checked: false,
    winnerName: "",
    description: "All Digits of 4, 5 and 6 columns in ticket",
  },
  {
    id: 7,
    winningName: "dinner",
    winningLabel: "Dinner",
    checked: false,
    winnerName: "",
    description: "All Digits of last three columns in ticket",
  },
  {
    id: 8,
    winningName: "even",
    winningLabel: "Even Numbers",
    checked: false,
    winnerName: "",
    description: "All EVEN Numbers in ticket",
  },
  {
    id: 9,
    winningName: "odd",
    winningLabel: "Odd Numbers",
    checked: false,
    winnerName: "",
    description: "All ODD Numbers in ticket",
  },
  {
    id: 10,
    winningName: "bp",
    winningLabel: "Blood Pressure",
    checked: false,
    winnerName: "",
    description: "Lowest and highest Number on ticket",
  },
  {
    id: 11,
    winningName: "luckySeven",
    winningLabel: "Lucky Seven",
    checked: false,
    winnerName: "",
    description: "Early Seven Numbers on ticket",
  },
  {
    id: 12,
    winningName: "fullHouse",
    winningLabel: "Full House - WInner",
    checked: false,
    winnerName: "",
    description: "All Digits in ticket",
  },
  {
    id: 13,
    winningName: "fullHouse2",
    winningLabel: "Full House - Runnerup",
    checked: false,
    winnerName: "",
    description: "All Digits in ticket",
  },
];

export const tambolaNumbers = {
  1: "Kelly's Eye",
  2: "One Little Duck",
  3: "Cup of Tea",
  4: "Knock at the Door",
  5: "Man Alive",
  6: "Half a Dozen",
  7: "Lucky 7",
  8: "Garden Gate",
  9: "Doctor's Orders",
  10: "Theresa's Den",
  11: "Legs Eleven",
  12: "One Dozen",
  13: "Unlucky for Some",
  14: "Valentine's Day",
  15: "Young and Keen",
  16: "Sweet Sixteen",
  17: "Dancing Queen",
  18: "Coming of Age",
  19: "Goodbye Teens",
  20: "One Score",
  21: "Key of the Door",
  22: "Two Little Ducks",
  23: "Thee and Me",
  24: "Two Dozen",
  25: "Duck and Dive",
  26: "Pick and Mix",
  27: "Gateway to Heaven",
  28: "Overweight",
  29: "Rise and Shine",
  30: "Dirty Gertie",
  31: "Get Up and Run",
  32: "Buckle My Shoe",
  33: "Dirty Knee",
  34: "Ask for More",
  35: "Jump and Jive",
  36: "Three Dozen",
  37: "More Than Eleven",
  38: "Christmas Cake",
  39: "Steps",
  40: "Naughty Forty",
  41: "Time for Fun",
  42: "Winnie the Pooh",
  43: "Down on Your Knees",
  44: "Droopy Drawers",
  45: "Halfway There",
  46: "Up to Tricks",
  47: "Four and Seven",
  48: "Four Dozen",
  49: "PC",
  50: "Bullseye",
  51: "Tweak of the Thumb",
  52: "Danny La Rue",
  53: "Stuck in the Tree",
  54: "Clean the Floor",
  55: "Snakes Alive",
  56: "Was She Worth It?",
  57: "Heinz Varieties",
  58: "Make Them Wait",
  59: "Brighton Line",
  60: "Five Dozen",
  61: "Baker's Bun",
  62: "Turn on the Screw",
  63: "Tickle Me 63",
  64: "Red Raw",
  65: "Old Age Pension",
  66: "Clickety-Click",
  67: "Made in Heaven",
  68: "Saving Grace",
  69: "Either Way Up",
  70: "Three Score and Ten",
  71: "Bang on the Drum",
  72: "Six Dozen",
  73: "Queen B",
  74: "Candy Store",
  75: "Strive and Strive",
  76: "Trombones",
  77: "Sunset Strip",
  78: "Heaven's Gate",
  79: "One More Time",
  80: "Eight and Blank",
  81: "Stop and Run",
  82: "Straight on Through",
  83: "Time for Tea",
  84: "Seven Dozen",
  85: "Staying Alive",
  86: "Between the Sticks",
  87: "Torquay in Devon",
  88: "Two Fat Ladies",
  89: "Nearly There",
  90: "Top of the Shop",
};
